" Sexy vim configs with pathogen
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

" ==> Global customizations.
set cursorcolumn                " highlight the screen column of the cursor
set cursorline                  " highlight the screen line of the cursor
set nocompatible                " No Vi Compatibility. That just sucks.
set backspace=indent,eol,start  " Fix backspace indentation
set t_Co=256                    " Convince Vim it can use 256 colors inside Gnome Terminal.
                                " Needs CSApprox plugin
let no_buffers_menu=1           " Menus I like :-)
                                " This must happen before the syntax system is enabled
                                " aunmenu Help.
                                " aunmenu Window.
set mouse=a                     " Enable mouse everywhere 
set mousehide                   " Hide mouse pointer while typing
set mousemodel=popup
map <MouseMiddle> <Esc>"*p      " Make mouse middle click paste without formatting it.
set foldmethod=indent           " Code Folding, everything folded by default
set foldlevel=99
set foldenable
set viminfo=!,'100,\"100,:20,<50,s10,h,n~/.viminfo " Better modes.  Remeber where we are, support yankring
set backupdir=~/.vim/sessions   " Move Backup Files to ~/.vim/sessions
set dir=~/.vim/sessions
set noswapfile                  " Turn off annoying swapfiles
set undodir=~/.vim/undodir      " Set persistent undo (v7.3 only)
set undofile
set enc=utf-8                   " utf-8 default encoding
set fileformats=unix,dos,mac    " Prefer unix over windows over os9 formats
if has('autocmd')               " Don't bell or blink(Courtesy: Cream Editor).
  autocmd GUIEnter * set vb t_vb=
endif
set scrolloff=5                 " Keep some more lines for scope

" ==> User interface.
function! GuiTabLabel()         " GUI Tab settings
  let label = ''
  let buflist = tabpagebuflist(v:lnum)
  if exists('t:title')
    let label .= t:title . ' '
  endif
  let label .= '[' . bufname(buflist[tabpagewinnr(v:lnum) - 1]) . ']'
  for bufnr in buflist
    if getbufvar(bufnr, '&modified')
      let label .= '+'
      break
    endif
  endfor
  return label
endfunction

set guitablabel=%{GuiTabLabel()}

syntax on                       " Enable Syntax Colors
if has("gui_running")
  set guifont=Mensch\ 10
else
  colorscheme mustang
endif

set background=dark
"let g:solarized_termtrans=1
let g:solarized_termcolors=256
let g:solarized_contrast="high"
let g:solarized_visibility="high"
colorscheme solarized
"colorscheme colorful256
"call togglebg#map("<F5>")

if has('gui_running')           " Set fixed height widht of gvim window
  set lines=46
endif

autocmd BufEnter * :syntax sync fromstart   " The PC is fast enough, do syntax highlight syncing from start

" Remember cursor position
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g`\"" | endif

" Enable hidden buffers
set hidden

" Enable automatic title setting for terminals
set title
set titleold="Terminal"
set titlestring=%F\ -\ Vim

" Enable filetype plugins and indention
filetype on
filetype plugin on

" Activate a permanent ruler 
set ruler

" Disable Toolbar, Scrollbar
set guioptions-=T
set guioptions-=r

" Disable the stupid pydoc preview window for the omni completion
set completeopt-=preview

" Disable the blinking cursor.
set gcr=a:blinkon0

" Highlight current line 
if has("gui_running")
  set cursorline
endif

set ttyfast

" Customize the wildmenu
set wildmenu
set wildignore=*.dll,*.o,*.pyc,*.bak,*.exe,*.jpg,*.jpeg,*.png,*.gif,*$py.class,*.class
set wildmode=list:full

" Go with smartindent if there is no plugin indent file.
set autoindent  smartindent
" But don't outdent hashes
inoremap # X#

" Global by default
set gdefault

" Better Search
set hlsearch
set incsearch
set showmatch

" Make the command line two lines high and change the statusline display to
" something that looks useful.
function! CWD()
    let curdir = substitute(getcwd(), '/home/bill', "~", "g")
    return curdir
endfunction

set cmdheight=2
set laststatus=2
set statusline=[%l,%v\ %P%M][CWD:\ %{CWD()}][FILE:\ %f]\ %r%h%w\ (%{&ff})\ %{fugitive#statusline()}\ %#warningmsg#%{SyntasticStatuslineFlag()}%*
set showcmd
set showmode
set number

" Tab Settings
set smarttab
set tabstop=4

" ==> Key maps.
let mapleader=","               "Set <leader> to ','
let maplocalleader="\\"         "Set <localleader> to '\'

" <F2> Global :: Save in all three modes
noremap  <F2> <Esc>:w<CR>
inoremap <F2> <Esc>:w<CR>
nnoremap <F2> <Esc>:w<CR>
vnoremap <F2> <Esc>:w<CR>


" Global :: <leader>bd to delete buffer
noremap <leader>bd <Esc>:bd<CR>
vnoremap <leader>bd <Esc>:bd<CR>

" Global :: Toggle pate with <F6>
set pastetoggle=<F6>

" Global :: Left/Right arrow keys change buffers in all modes
noremap <Left> <Esc>:bp<CR>
inoremap <Left> <Esc>:bp<CR>
nnoremap <Left> <Esc>:bp<CR>
vnoremap <Left> <Esc>:bp<CR>

noremap <Right> <Esc>:bn<CR>
inoremap <Right> <Esc>:bn<CR>
nnoremap <Right> <Esc>:bn<CR>
vnoremap <Right> <Esc>:bn<CR>

" Global :: Rempam Vim 0 to ^
noremap 0 ^

" Global :: Hide matches on <leader>space
nnoremap <leader><space> :nohlsearch<cr>

" Global :: Remove trailing whitespace on <leader>S
nnoremap <leader>S :%s/\s\+$//<cr>:let @/=''<CR>

" Global :: <leader>v selects the just pasted text
nnoremap <leader>v V`]

" Global :: Copy/Paste to and from Desktop Environment
noremap <leader>yy "+y
noremap <leader>pp "+gP

" Global :: Quit window on <leader>q
nnoremap <leader>q :q<CR>

" Global :: Set working directory
nnoremap <leader>. :lcd %:p:h<CR>

" Global :: Make shift-insert work like in Xterm
map <S-Insert> <MiddleMouse>
map! <S-Insert> <MiddleMouse>

" Global :: Split window management
nnoremap <leader>w <C-w>v<C-w>l
nnoremap <leader>W <C-w>s
nnoremap <leader>s :new<CR>

" Global :: ; is an alias for :
nnoremap ; :

" Global :: ,st is an aliasd for :sts <tag name>
function! Sts()
  let st = expand("<cword>")
  exe "sts ".st
endfunction
nmap <leader>st : call Sts()<CR>

" Global :: ,tj is an aliased for :tj <tag name>
function! Tj()
  let st = expand("<cword>")
  exe "tj ".st
endfunction
nmap <leader>tj : call Tj()<CR>
noremap  <F3> <Esc>:call Tj()<CR>
inoremap <F3> <Esc>:call Tj()<CR>
nnoremap <F3> <Esc>:call Tj()<CR>
vnoremap <F3> <Esc>:call Tj()<CR>

" ==> Plugin setup and key maps.

" <F3> Plugin :: ConqueTerm Launches ConqueTermVSplit in virtal split window with bash.
noremap  <F4> <Esc>:ConqueTermVSplit bash<CR>
inoremap <F4> <Esc>:ConqueTermVSplit bash<CR>
nnoremap <F4> <Esc>:ConqueTermVSplit bash<CR>
vnoremap <F4> <Esc>:ConqueTermVSplit bash<CR>

" <F4> Plugin :: ConqueTerm Launches ConqueTermSplit in horiz. split windw with bash.
"noremap  <F4> <Esc>:ConqueTermSplit bash<CR>
"inoremap <F4> <Esc>:ConqueTermSplit bash<CR>
"nnoremap <F4> <Esc>:ConqueTermSplit bash<CR>
"vnoremap <F4> <Esc>:ConqueTermSplit bash<CR>

" <F5> Plugin :: ConqueueTerm Execute current file in Conque.
let g:ConqueTerm_ExecFileKey = '<F5>'

" <leader>o, <leader>O, <leader>m Plugin :: Command-t
noremap <leader>o <Esc>:CommandT<CR>
noremap <leader>O <Esc>:CommandTFlush<CR>
noremap <leader>m <Esc>:CommandTBuffer<CR>

" <leader>t Plugin :: Toggle NERDtree.
nnoremap <leader>t :NERDTreeToggle<CR>
let NERDTreeIgnore=['\~$', '\.pyc$', '\.pyo$', '\.class$', 'pip-log\.txt$', '\.o$']

" Plugin :: Taglist
"let Tlist_Compact_Format = 1
"let Tlist_Ctags_Cmd = 'ctags'
"let Tlist_Enable_Fold_Column = 0
"let Tlist_Exist_OnlyWindow = 1
"let Tlist_File_Fold_Auto_Close = 0
"let Tlist_sort_type = "name"
"let Tlist_Use_Right_Window = 1
"let TlistHighlightTag = 1
"let Tlist_Width = 40
"let Tlist_GainFocus_On_ToggleOpen = 1
"nnoremap <leader>l :Tlist<CR>

" <leader>l Plugin :: Tagbar
let g:tagbar_usearrows = 1
nnoremap <leader>l :TagbarToggle<CR>

" Plugin :: netrw hide some files and remove stupid help
let g:netrw_list_hide='^\.,.\(pyc\|pyo\|o\)$'

let g:miniBufExplMapWindowNavVim = 1 
let g:miniBufExplMapWindowNavArrows = 1 
let g:miniBufExplMapCTabSwitchBufs = 1 
let g:miniBufExplModSelTarget = 1 

" Plugin :: clang_complete
let g:SuperTabDefaultCompletionType = "context"
let g:clang_auto_select = 1
let g:clang_snippets = 1
let g:clang_trailing_placeholder = 1

" ==> Local configuration for each type of files.

" Disable the colorcolumn when switching modes.  Make sure this is the
" first autocmd for the filetype here
autocmd FileType * setlocal colorcolumn=0

" python support
" --------------
"  don't highlight exceptions and builtins. I love to override them in local
"  scopes and it sucks ass if it's highlighted then. And for exceptions I
"  don't really want to have different colors for my own exceptions ;-)
autocmd FileType python setlocal expandtab shiftwidth=4 tabstop=4 colorcolumn=79
\ formatoptions+=croq softtabstop=4 smartindent
\ cinwords=if,elif,else,for,while,try,except,finally,def,class,with
let python_highlight_all=1
let python_highlight_exceptions=0
let python_highlight_builtins=0
autocmd FileType pyrex setlocal expandtab shiftwidth=4 tabstop=4 softtabstop=4 smartindent cinwords=if,elif,else,for,while,try,except,finally,def,class,with

" ruby support
" ------------
autocmd FileType ruby setlocal expandtab shiftwidth=2 tabstop=2 softtabstop=2 colorcolumn=79

" template language support (SGML / XML too)
" ------------------------------------------
" and disable taht stupid html rendering (like making stuff bold etc)
fun! SelectHTML()
  let n = 1
  while n < 50 && n < line("$")
    " check for jinja
    if getline(n) =~ '{%\s*\(extends\|block\|macro\|set\|if\|for\|include\|trans\)\>'
      set ft=htmljinja
      return
    endif
    " check for mako
    if getline(n) =~ '<%\(def\|inherit\)'
      set ft=mako
      return
    endif
    " check for genshi
    if getline(n) =~ 'xmlns:py\|py:\(match\|for\|if\|def\|strip\|xmlns\)'
      set ft=genshi
      return
    endif
    let n = n + 1
  endwhile
  " go with html
  set ft=html
endfun

autocmd FileType html,xhtml,xml,htmldjango,htmljinja,eruby,mako setlocal expandtab shiftwidth=2 tabstop=2 softtabstop=2
autocmd BufNewFile,BufRead *.rhtml setlocal ft=eruby
autocmd BufNewFile,BufRead *.mako setlocal ft=mako
autocmd BufNewFile,BufRead *.tmpl setlocal ft=htmljinja
autocmd BufNewFile,BufRead *.py_tmpl setlocal ft=python
autocmd BufNewFile,BufRead *.html,*.htm  call SelectHTML()
let html_no_rendering=1

autocmd FileType html,htmldjango,htmljinja,eruby,mako let b:closetag_html_style=1
autocmd FileType html,xhtml,xml,htmldjango,htmljinja,eruby,mako source ~/.vim/bundle/closetag/plugin/closetag.vim

" CSS
" ---
autocmd FileType css setlocal expandtab shiftwidth=4 tabstop=4 softtabstop=4

" rst
" ---
autocmd BufNewFile,BufRead *.rst setlocal ft=rst
autocmd FileType rst setlocal expandtab shiftwidth=4 tabstop=4 softtabstop=4 colorcolumn=79
\ formatoptions+=nqt textwidth=74

" markdown
" ---
autocmd BufNewFile,BufRead *.txt,*.markdown,*.md setlocal ft=markdown colorcolumn=79
autocmd FileType rst setlocal expandtab shiftwidth=4 tabstop=4 softtabstop=4 colorcolumn=79

" vim
" ---
autocmd FileType vim setlocal expandtab shiftwidth=2 tabstop=8 softtabstop=2 colorcolumn=79

" Javascript
" ----------
autocmd FileType javascript setlocal expandtab shiftwidth=2 tabstop=2 softtabstop=2 colorcolumn=79
let javascript_enable_domhtmlcss=1

" c/c++
" ---
autocmd FileType c,cpp setlocal smartindent smarttab tabstop=4 shiftwidth=4 colorcolumn=79

